# Site
name: "Vuong Tuyen"
title: "Tuyen"
description: "Đây là Blog cá nhân của Tuyên"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
google_analytics: 'UA-137800441-1'
disqus: 'Vuongquangtuyen'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tuyen:
    name: Tuyen
    display_name: Vuong Tuyen
    avatar: 'assets/images/avatar.png'
    gravatar: 2298dfedff6d974d1394901358038f49
    email: tuyenvq.cntt@gmail.com
    web: https://fb.com/vuongquangtuyen
    twitter: https://twitter.com/tuyenvq
    description: "Xin chào! Tôi là Tuyên."

# Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]