# Website details
name: Vương Quang Tuyên
description: Chia sẻ là học tập.
url: https://tuyenga.github.io
author:
  name: Lucas Vương
  fullname: Vương Quang Tuyên
  email: Vuongquangtuyendz@gmail.com
  github: tuyenga
  twitter: '@sealaunchiris'
  linkedin: Vuongquangtuyen
  bio: Đam mê là điều tạo nên những sản phẩm tuyệt vời chúng giúp nhiều người nâng cao cuộc sống của họ.

twitter:
  username: sealaunchiris

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge
timezone: Asia/Ho_Chi_Minh
repository: Tuyenga/Tuyenga.github.io

paginate: 10
paginateLabel: page
paginate_path: 'page/:num'
permalink: /:categories/:year/:month/:day/:title
baseurl:

# Includes
addthisId: 'ra-59232f96e44fd867'
disqusShortname: 'Vuongquangtuyen'
googleAnalyticsId: 'UA-99596857-1'

# Search engine verifications
bing: ''
yandex: ''
google: ''

#Sitemap
sitemap:
  file: '/sitemap.xml'
  exclude:
    - '/404.html'
  include_posts:
    - '/index.html'
  change_frequency_name: 'daily'
  priority_name: '1.00'

gems:
  - github-pages
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
